# Generated by Django 2.2.5 on 2019-11-25 06:25

import cameras.helpers.camera_status_class
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('ip', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('ON', 'on'), ('OFF', 'off')], default=cameras.helpers.camera_status_class.CameraStatus('off'), max_length=124)),
                ('date_added', models.DateField()),
                ('date_changed', models.DateField(null=True)),
                ('place', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
