# Generated by Django 2.2.5 on 2019-11-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='date_changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='status',
            field=models.CharField(choices=[('ON', 'on'), ('OFF', 'off')], default='off', max_length=124),
        ),
    ]
