# Generated by Django 2.2.5 on 2019-12-07 06:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=512)),
                ('cookies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), null=True, size=None)),
            ],
        ),
    ]
