# Generated by Django 2.2.5 on 2019-12-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
